kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraMounts:
    # hostPath must match the path to the dist folder of the portainer project
  - hostPath: /home/baron_l/projects/pro/portainer/dist
    containerPath: /portainer/app
  extraPortMappings:
  - containerPort: 9000
    # hostPort will be the port to use to access portainer instance at localhost:hostPort
    hostPort: 9000
    listenAddress: "0.0.0.0"
    protocol: TCP
- role: worker
- role: worker
